package farever:addon@1.1.0;

/// The imports and callbacks available to a Farever add-on.
world farever-addon {
    import runtime;
    import assets;
    import canvas-options;

    import game;
    import player;
    import party;
    import camera;
    import combat;
    import instance-session;
    import zone;
    import windows;
    import %map;

    import bus;
    import dependencies;
    import config;
    import chat;
    export plugin;
}
