[package]
name = "farever-more-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossbeam-queue = "0.3"
egui.workspace = true
egui_extras.workspace = true
farever-more-api = { path = "../farever-more-api" }
farever-more-manifest = { path = "../farever-more-manifest" }
farever-db = { path = "../farever-db" }
farever-api-inspector = { path = "../farever-api-inspector" }
hex.workspace = true
image.workspace = true
memchr.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ttf-parser = "0.25"
wasmtime.workspace = true
wasm-metadata.workspace = true
windows-sys.workspace = true

[target.'cfg(windows)'.dependencies]
minhook = "0.9.0"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
] }
