// Generated by `cargo run -p farever-db --bin extract-db`.
// Do not edit by hand: regenerate from the installed game instead.
// Read through `farever_db::Inventory`, never directly.
use super::*;

/// Every aptitude the game defines, sorted by id.
pub static RECORDS: &[Aptitude] = &[
    Aptitude { id: "ArPen", flags: 0 },
    Aptitude { id: "AssCle", flags: 0 },
    Aptitude { id: "AssWiz", flags: 0 },
    Aptitude { id: "Assassin", flags: 1 },
    Aptitude { id: "Cleric", flags: 1 },
    Aptitude { id: "Crit", flags: 0 },
    Aptitude { id: "Fervor", flags: 0 },
    Aptitude { id: "FigAss", flags: 0 },
    Aptitude { id: "FigCle", flags: 0 },
    Aptitude { id: "FigWiz", flags: 0 },
    Aptitude { id: "Fighter", flags: 1 },
    Aptitude { id: "MaPen", flags: 0 },
    Aptitude { id: "Vita", flags: 0 },
    Aptitude { id: "WizCle", flags: 0 },
    Aptitude { id: "Wizard", flags: 1 },
];
