// Generated by `cargo run -p farever-db --bin extract-db`.
// Do not edit by hand: regenerate from the installed game instead.
// Read through `farever_db::Inventory`, never directly.
// Game build: 25257040
// data.cdb checksum 0xc383de7f, 4902490 bytes, 426 sheets
use super::BuildSource;

/// Which game build the extracted tables came from.
pub const BUILD: BuildSource = BuildSource {
    steam_build_id: Some("25257040"),
    cdb_checksum: 3280199295,
    cdb_size: 4902490,
    sheets: 426,
};
