// Generated by `cargo run -p farever-db --bin extract-db`.
// Do not edit by hand: regenerate from the installed game instead.
// Read through `farever_db::Inventory`, never directly.
use super::{Gatherable, GatherableKind};

/// Every gather node the game defines, in `data.cdb` order.
pub static RECORDS: &[Gatherable] = &[
    Gatherable { id: "Ore", kind: GatherableKind::Ore, inherit: None, name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Plant", kind: GatherableKind::Plant, inherit: None, name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Ore_Small", kind: GatherableKind::Ore, inherit: Some("Ore"), name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: Some(0), hit_points: Some(60), respawn_time: Some(120) },
    Gatherable { id: "Ore_Medium", kind: GatherableKind::Ore, inherit: Some("Ore"), name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: Some(1), hit_points: Some(120), respawn_time: Some(240) },
    Gatherable { id: "Ore_Big", kind: GatherableKind::Ore, inherit: Some("Ore"), name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: Some(2), hit_points: Some(200), respawn_time: Some(360) },
    Gatherable { id: "Ore_Copper_Small", kind: GatherableKind::Ore, inherit: Some("Ore_Small"), name: Some("Copper Cluster"), model: None, loot: None, hit_loot: Some("Ore_Copper"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Ore_Copper_Large", kind: GatherableKind::Ore, inherit: Some("Ore_Big"), name: Some("Copper Lode"), model: None, loot: None, hit_loot: Some("Ore_Copper"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Ore_Iron_Small", kind: GatherableKind::Ore, inherit: Some("Ore_Small"), name: Some("Iron Cluster"), model: None, loot: None, hit_loot: None, required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Ore_Iron_Big", kind: GatherableKind::Ore, inherit: Some("Ore_Big"), name: Some("Iron Lode"), model: None, loot: None, hit_loot: None, required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Ore_Tin_Small", kind: GatherableKind::Ore, inherit: Some("Ore_Small"), name: Some("Tin Cluster"), model: None, loot: None, hit_loot: Some("Ore_Tin"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Ore_Tin_Large", kind: GatherableKind::Ore, inherit: Some("Ore_Big"), name: Some("Tin Lode"), model: None, loot: None, hit_loot: Some("Ore_Tin"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Tungstene", kind: GatherableKind::Ore, inherit: Some("Ore_Small"), name: Some("Tungstene Deposit"), model: None, loot: None, hit_loot: Some("Tungstene"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Plant_Small", kind: GatherableKind::Plant, inherit: Some("Plant"), name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: Some(0), hit_points: Some(60), respawn_time: Some(120) },
    Gatherable { id: "Plant_Large", kind: GatherableKind::Plant, inherit: Some("Plant"), name: None, model: None, loot: None, hit_loot: None, required_tool: None, size: Some(2), hit_points: Some(200), respawn_time: Some(360) },
    Gatherable { id: "Madrigold_Small", kind: GatherableKind::Plant, inherit: Some("Plant_Small"), name: Some("Madrigold Sprout"), model: None, loot: None, hit_loot: Some("Madrigold"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Madrigold_Large", kind: GatherableKind::Plant, inherit: Some("Plant_Large"), name: Some("Madrigold Bush"), model: None, loot: None, hit_loot: Some("Madrigold"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Lavendula_Small", kind: GatherableKind::Plant, inherit: Some("Plant_Small"), name: Some("Lavendula Sprout"), model: None, loot: None, hit_loot: Some("Lavendula"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Lavendula_Large", kind: GatherableKind::Plant, inherit: Some("Plant_Large"), name: Some("Lavendula Bush"), model: None, loot: None, hit_loot: Some("Lavendula"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "AncientThyme_Small", kind: GatherableKind::Plant, inherit: Some("Plant_Small"), name: Some("Ancient Thyme Sprout"), model: None, loot: None, hit_loot: Some("AncientThyme"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "AncientThyme_Large", kind: GatherableKind::Plant, inherit: Some("Plant_Large"), name: Some("Ancient Thyme Bush"), model: None, loot: None, hit_loot: Some("AncientThyme"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Zealotus_Small", kind: GatherableKind::Plant, inherit: Some("Plant_Small"), name: Some("Zealotus Sprout"), model: None, loot: None, hit_loot: Some("Zealotus"), required_tool: None, size: None, hit_points: None, respawn_time: None },
    Gatherable { id: "Zealotus_Large", kind: GatherableKind::Plant, inherit: Some("Plant_Large"), name: Some("Zealotus Bush"), model: None, loot: None, hit_loot: Some("Zealotus"), required_tool: None, size: None, hit_points: None, respawn_time: None },
];
