// Generated by `cargo run -p farever-db --bin extract-db`.
// Do not edit by hand: regenerate from the installed game instead.
// Read through `farever_db::Inventory`, never directly.
use super::*;

/// Every rarity the game defines, sorted by id.
pub static RECORDS: &[Rarity] = &[
    Rarity { id: "Common", brackets: &[] },
    Rarity { id: "Epic", brackets: &[RarityBracket { min_level: 1, max_level: 10, chance: 0.0 }, RarityBracket { min_level: 11, max_level: 30, chance: 0.19 }, RarityBracket { min_level: 31, max_level: 49, chance: 0.25 }, RarityBracket { min_level: 50, max_level: 10000, chance: 0.35 }] },
    Rarity { id: "Legendary", brackets: &[RarityBracket { min_level: 1, max_level: 10, chance: 0.0 }, RarityBracket { min_level: 11, max_level: 30, chance: 0.01 }, RarityBracket { min_level: 31, max_level: 49, chance: 0.01 }, RarityBracket { min_level: 50, max_level: 10000, chance: 0.05 }] },
    Rarity { id: "Rare", brackets: &[RarityBracket { min_level: 1, max_level: 10, chance: 0.6 }, RarityBracket { min_level: 11, max_level: 30, chance: 0.5 }, RarityBracket { min_level: 31, max_level: 49, chance: 0.59 }, RarityBracket { min_level: 50, max_level: 10000, chance: 0.6 }] },
    Rarity { id: "Uncommon", brackets: &[RarityBracket { min_level: 1, max_level: 10, chance: 0.4 }, RarityBracket { min_level: 11, max_level: 30, chance: 0.3 }, RarityBracket { min_level: 31, max_level: 49, chance: 0.15 }, RarityBracket { min_level: 50, max_level: 10000, chance: 0.0 }] },
];
