// Generated by `cargo run -p farever-db --bin extract-db`.
// Do not edit by hand: regenerate from the installed game instead.
// Read through `farever_db::Inventory`, never directly.
use super::*;

/// Every enemy family the game defines, sorted by id.
pub static RECORDS: &[UnitType] = &[
    UnitType { id: "Bee", name: Some("Bees"), loot_table: Some("Bee") },
    UnitType { id: "Boar", name: Some("Boars"), loot_table: Some("Boar") },
    UnitType { id: "Coyote", name: Some("Coyotes"), loot_table: Some("Coyotes") },
    UnitType { id: "Crab", name: Some("Crabs"), loot_table: Some("Crab") },
    UnitType { id: "Crimson", name: Some("Crimson"), loot_table: Some("Crimson") },
    UnitType { id: "Critter", name: Some("Companions"), loot_table: None },
    UnitType { id: "Demon", name: Some("Demons"), loot_table: Some("Demon") },
    UnitType { id: "Demon_Rift", name: Some("Demons"), loot_table: Some("Demon_Rift") },
    UnitType { id: "Environment", name: Some(""), loot_table: None },
    UnitType { id: "FireGolems", name: Some("Fire Golems"), loot_table: Some("FireGolems") },
    UnitType { id: "Golem", name: Some("Golems"), loot_table: Some("EarthGolems") },
    UnitType { id: "Human", name: Some(""), loot_table: None },
    UnitType { id: "Kobold", name: Some("Kobolds"), loot_table: Some("Kobold") },
    UnitType { id: "Manfish", name: Some("Nepsids"), loot_table: Some("Manfish") },
    UnitType { id: "Mount", name: Some("Mount"), loot_table: None },
    UnitType { id: "Ogre", name: Some("Ogres"), loot_table: None },
    UnitType { id: "Skunk", name: Some("Skunks"), loot_table: Some("Skunk") },
    UnitType { id: "Slime", name: Some("Slimes"), loot_table: Some("Slime") },
    UnitType { id: "Spirit", name: Some("Spirits"), loot_table: Some("Spirits") },
    UnitType { id: "Sprouts", name: Some("Sprouts"), loot_table: Some("Sprouts") },
    UnitType { id: "Swarowl", name: Some("Bat"), loot_table: Some("Bee") },
    UnitType { id: "Totem", name: Some(""), loot_table: None },
    UnitType { id: "WaterGolems", name: Some("Water Golems"), loot_table: Some("WaterGolems") },
    UnitType { id: "WindGolems", name: Some("Wind Golems"), loot_table: Some("WindGolems") },
    UnitType { id: "Wolf", name: Some("Wolves"), loot_table: Some("Wolf") },
];
